spring:
  profiles:
    active: production
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/star?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
server:
  port: 80
  session:
    timeout: 3600