# 数据库访问配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/star?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:  
    database: 0  
    host: 127.0.0.1  
    port: 6379  
    password: 
    timeout: 5000   

# 服务器的基本属性配置
server:
  port: 80
  session:
    timeout: 1800

# druid连接池的自定义配置
druid:
  loginUsername: admin
  loginPassword: admin
  resetEnable: false
#  allow: 127.0.0.1
#  deny: 127.0.0.1

# 关于系统web的一些基本设置
web:
  logEnable: true
  resources: classpath:/static/
  crossDomain:
    origin: GET,HEAD,POST,PUT,DELETE,OPTIONS
    maxAge: 3600
  
# 关于权限框架的配置 
security:
  enable: true
  csrf: false
  iframe: true
  formLogin:
    enable: true
    skipModel: redirect
    loginPage: /login.html
    loginProcessingUrl: /login.do
    defaultSuccessUrl: /index.html
    failureUrl: /login.html?error=true
    usernameParameter: username
    passwordParameter: password
    verificationCode: 
      enable: true
      parameter: kaptcha
    rememberMe:
      enable: true
      key: loverqi_star
      rememberMeParameter: remember-me
      tokenValiditySeconds: 604800
  logout:
    enable: true
    logoutUrl: /unlogin.do
    logoutSuccessUrl: /login.html?msg=1
  sessionManagement:
    enable: true
    maximumSessions: 1
    expiredUrl: /login.html?msg=2
  ignorings: /getKaptchaImg.do

# 设置文件上传限制
file:
  maxFileSize: 10MB
  maxRequestSize: 100MB
  
# 设置Swagger相关属性
swagger:
  enable: true
  basePackage: cn.loverqi.star.web.controller
  title: star快速开发平台对外开放接口API文档
  description: 对外开放接口API文档主要使用于安卓、ios、微信公众平台、微信小程序和支付小程序及前后端分离模式的开发。
  license: loverqi.cn
  licenseUrl: https://github.com/loverqi/star
  version: 1.0
  
    
    