# 数据库访问配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/star?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

# 服务器的基本属性配置
server:
  port: 80
  session:
    timeout: 3600

# druid连接池的自定义配置
druid:
  loginUsername: admin
  loginPassword: admin
  resetEnable: false
#  allow: 127.0.0.1
#  deny: 127.0.0.1

# 设置文件上传限制
file:
  maxFileSize: 10MB
  maxRequestSize: 100MB

# 关于系统web的一些基本设置
web:
  crossDomain:
    origin: GET,HEAD,POST,PUT,DELETE,OPTIONS
    maxAge: 3600
  resources: classpath:/static/

# 设置Swagger相关属性
swagger:
  show: true
  basePackage: cn.loverqi.star.web.controller
  title: star快速开发平台对外开放接口API文档
  description: 对外开放接口API文档主要使用于安卓、ios、微信公众平台、微信小程序和支付小程序及前后端分离模式的开发。
  license: loverqi.cn
  licenseUrl: https://github.com/loverqi/star
  version: 1.0
  
    
    